### ISSUE TITLE
Youtube Video Section (Use the Drone video for now, will have another video for you soon to use)

### ISSUE THREAD

**Issue by agiron123** [BeamLabs/Kingsland-Farm#2]
Make the video span most of the whole screen. I don't have an exact size in mind here. Use good taste.

Link to the video:
https://www.youtube.com/watch?v=usZuHDDMDJ8&feature=em-share_video_user

**Comment by Mousecop** [comment]
Waiting on PR.

**Comment by agiron123** [comment]
Looks good
